// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZO4874BsJaxR36XOM-IBgl47EsCNgFA',
    appId: '1:88051254969:web:334e99d1507c05a6213d68',
    messagingSenderId: '88051254969',
    projectId: 'bookingbusapp-ed0e1',
    authDomain: 'bookingbusapp-ed0e1.firebaseapp.com',
    storageBucket:
        'bookingbusapp-ed0e1.appspot.com', // ✅ Sửa lại đúng định dạng
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcHgaZF1xk9doML1RiL_XNNf1hNZfZNgQ',
    appId: '1:88051254969:android:63bb7177093a84e6213d68',
    messagingSenderId: '88051254969',
    projectId: 'bookingbusapp-ed0e1',
    storageBucket:
        'bookingbusapp-ed0e1.appspot.com', // ✅ Sửa lại đúng định dạng
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFO1jP0J1etcbuTA7RpgFCTepw-BkdqA',
    appId: '1:88051254969:ios:c5d416eee6c021e8213d68',
    messagingSenderId: '88051254969',
    projectId: 'bookingbusapp-ed0e1',
    storageBucket:
        'bookingbusapp-ed0e1.appspot.com', // ✅ Sửa lại đúng định dạng
    androidClientId:
        '88051254969-6vdriv9h3cd1q232q08gn5cpdsv58e54.apps.googleusercontent.com',
    iosClientId:
        '88051254969-22kdgpj8aldulu1nbs0apg6ueq6quff7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFO1jP0J1etcbuTA7RpgFCTepw-BkdqA',
    appId: '1:88051254969:ios:c5d416eee6c021e8213d68',
    messagingSenderId: '88051254969',
    projectId: 'bookingbusapp-ed0e1',
    storageBucket:
        'bookingbusapp-ed0e1.appspot.com', // ✅ Sửa lại đúng định dạng
    androidClientId:
        '88051254969-6vdriv9h3cd1q232q08gn5cpdsv58e54.apps.googleusercontent.com',
    iosClientId:
        '88051254969-22kdgpj8aldulu1nbs0apg6ueq6quff7.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZO4874BsJaxR36XOM-IBgl47EsCNgFA',
    appId: '1:88051254969:web:e153344c53ed5910213d68',
    messagingSenderId: '88051254969',
    projectId: 'bookingbusapp-ed0e1',
    authDomain: 'bookingbusapp-ed0e1.firebaseapp.com',
    storageBucket:
        'bookingbusapp-ed0e1.appspot.com', // ✅ Sửa lại đúng định dạng
  );
}
